# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StyleViewer
                                 A QGIS plugin
 This plugin gathers embedded styles and shows them
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-29
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : leonid.kolesnichenko@nextgis.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StyleViewer class from file StyleViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .style_viewer import StyleViewer
    return StyleViewer(iface)
