"""
/***************************************************************************
 StyleViewer
                                 A QGIS plugin
 This plugin gathers embedded styles and shows them
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-29
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : leonid.kolesnichenko@nextgis.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from osgeo import ogr
from qgis.core import QgsMapLayerType
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from . import about_dialog

# Import the code for the dialog
from .qgis_ogrstyle_dialog import QgisOgrStyleDialog

# Initialize Qt resources from file resources.py
from .resources import *  # noqa


class QgisOgrStyle:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.actionAbout = None
        self.renderer = None
        self.dlg = None
        self.layer = None
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)  # noqa
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(  # noqa
            self.plugin_dir, "i18n", f"StyleViewer_{locale}.qm"
        )

        if os.path.exists(locale_path):  # noqa
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Style Viewer")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def about(self):
        dialog = about_dialog.AboutDialog(os.path.basename(self.plugin_dir))  # noqa
        dialog.exec_()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("StyleViewer", message)

    def add_action(  # noqa
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,  # noqa
        add_to_menu=True,  # noqa
        add_to_toolbar=True,  # noqa
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):  # noqa
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/style_viewer/icon.png"
        self.add_action(
            icon_path,
            text=self.tr("Style Viewer"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        self.first_start = True
        self.actionAbout = QAction(
            self.tr("About plugin…"), self.iface.mainWindow()
        )
        self.iface.addPluginToMenu("Style Viewer", self.actionAbout)
        self.actionAbout.triggered.connect(self.about)

    def about(self):  # noqa
        dialog = about_dialog.AboutDialog(os.path.basename(self.plugin_dir))  # noqa
        dialog.exec_()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(self.tr("&Style Viewer"), action)
            self.iface.removeToolBarIcon(action)
        self.iface.removePluginMenu("Style Viewer", self.actionAbout)
        self.actionAbout.deleteLater()

    def closeEvent(self, event):  # noqa
        # Disconnect the signal before the window is closed
        if self.layer:
            self.layer.selectionChanged.disconnect(self.selection_changed)
        event.accept()  # Proceed with the close event

    def selection_changed(self):
        if self.renderer.type() == "embeddedSymbol":
            ds_uri = self.layer.dataProvider().dataSourceUri()
            ogr_layer = ogr.Open(ds_uri)
            feature = ogr_layer[0].GetNextFeature()
            self.dlg.StyleLineEdit.setText(feature.GetStyleString())

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation)
        # and keep reference
        # Only create GUI ONCE in callback,
        # so that it will only load when the plugin is started
        self.dlg = QgisOgrStyleDialog()

        # show the dialog
        self.dlg.show()
        self.dlg.closeEvent = self.closeEvent

        # Run the dialog event loop
        # See if OK was pressed
        # Get the active layer (make sure it's a vector layer)
        self.layer = self.iface.activeLayer()
        if self.layer and self.layer.type() == QgsMapLayerType.VectorLayer:
            # Connect the 'selectionChanged'
            # signal to the 'selection_changed' function
            self.layer.selectionChanged.connect(self.selection_changed)
            self.renderer = self.iface.activeLayer().renderer()
